# graph/state.py
"""
Agent State Definition - Production Verified

This TypedDict defines the shared state schema used across the entire LangGraph agent.
All nodes read from and write to this state.
"""

import operator
from typing import Annotated, Any, Dict, List, NotRequired, TypedDict


class AgentState(TypedDict):
    """
    The central state object passed between all nodes in the agent graph.

    Fields:
        query: The original user query (input)
        intent: Classified intent from classify node
        plan: List of steps generated by reasoning node
        retrieved_docs: Documents returned by RAG node (appended via operator.add)
        tool_outputs: Cumulative results from execution nodes (appended via operator.add)
        synthesized_response: Final coherent answer from merge node
        validation_result: Boolean result from critic/validation node
        iterations: Counter for validation loops to prevent infinite cycles
        final_output: Final refined answer after all gates
    """

    # Core input
    query: str

    # Classification & Planning
    intent: str
    plan: List[str]

    # ==================== NEW FIELD (Added for extract_filters node) ====================
    # Metadata filters extracted early in the pipeline (after classification).
    # Used by planner_node and retrieval_node for efficient, targeted search.
    # Example: {"regulators": ["SEC", "FCA"], "year": 2024, "doc_types": ["speech"], "jurisdiction": "US"}
    filters: Dict[str, Any]
    # ===================================================================================

    # Route chosen by router_node: "rag" | "structured" | "calculation" | "other"
    # Used to branch after retrieval (tools vs structured vs calculation)
    route: NotRequired[str]

    # Retrieval & Tool Results
    # Using Annotated + operator.add ensures that if multiple nodes
    # find documents or tool results, they are all preserved in a list.
    retrieved_docs: Annotated[List[Dict[str, Any]], operator.add]
    tool_outputs: Annotated[List[Dict[str, Any]], operator.add]

    # Synthesis & Validation
    synthesized_response: str
    validation_result: bool

    # Loop Control
    # This is critical for the decide_end logic in builder.py
    # Every time the critic runs, it should return {"iterations": 1}
    iterations: Annotated[int, operator.add]

    # Feedback from validation when invalid (reason from critic) — planner uses to adjust
    validation_feedback: NotRequired[str]

    # Optional final output
    final_output: str
